language: node_js
node_js:
  - lts/*

jobs:
  fast_finish: true
  include:
    # 10.15.5
    - os: osx
      osx_image: xcode11.6
    #10.14.6
    - os: osx
      osx_image: xcode11.3

branches:
  only:
  - master

install: 
    - safaridriver --version
    - sudo safaridriver --enable
    - ./.circleci/build.sh
    - npm i -g webdriver-manager
    - webdriver-manager update --chrome=false --gecko=false
    - npm i -g http-server

before_script:
    - webdriver-manager start --detach
    - http-server dist &
    - sleep 10
    
script:
    - cd tests
    - npm run test -- --override '{"helpers":{"WebDriver":{"hostname":"localhost","browser":"safari","url":"http://localhost:8080"}}}'
    
after_script:
    - webdriver-manager shutdown
